### ISSUE TITLE
is_infix test in js_of_ast is broken

### ISSUE THREAD

**Issue by brabalan** [jscert/jsexplain#12]
The is_infix function compares directly locations, which is a record with many fields. It's a miracle that it worked until now.

We should directly compare the line number and column number inside the locations.

**Comment by brabalan** [comment]
This is fixed in master. Should we cherry pick the fix to the proxies branch? (Or we can just copy the code, as the fix was iterated over several commits.)

If we copy the code, we should copy the tests as well.

**Comment by IgnoredAmbience** [comment]
Cherry-picked into es2016-proxies
