### ISSUE TITLE
use shadowing for state

### ISSUE THREAD

**Issue by brabalan** [jscert/jsexplain#15]
We should always use shadowing for state. For instance
``` ocaml
and run_binary_op_add s c v1 v2 =
  let%spec (s1, (w1, w2)) = (convert_twice_primitive s c v1 v2) in
  if  (type_compare (type_of w1) Coq_type_string)
   || (type_compare (type_of w2) Coq_type_string)
  then let%spec (s2, (str1, str2)) = (convert_twice_string s1 c w1 w2) in
    res_out s2 (res_val (Coq_value_string (strappend str1 str2)))
  else let%spec (s2, (n1, n2)) = (convert_twice_number s1 c w1 w2) in
    res_out s2 (res_val (Coq_value_number (n1 +. n2)))
```
should be
``` ocaml
and run_binary_op_add s c v1 v2 =
  let%spec (s, (w1, w2)) = (convert_twice_primitive s c v1 v2) in
  if  (type_compare (type_of w1) Coq_type_string)
   || (type_compare (type_of w2) Coq_type_string)
  then let%spec (s, (str1, str2)) = (convert_twice_string s c w1 w2) in
    res_out s (res_val (Coq_value_string (strappend str1 str2)))
  else let%spec (s, (n1, n2)) = (convert_twice_number s c w1 w2) in
    res_out s (res_val (Coq_value_number (n1 +. n2)))
```

**Comment by brabalan** [comment]
Dealt with 07f480c1dc1758afb7a31bbe53b838ba95131221

**Comment by IgnoredAmbience** [comment]
Shadowing is broken when binding to variables in patterns. This may also apply to tuple patterns and elsewhere in the codebase.

`ppf_match_binders` needs to be changed to only use `var` if not shadowing, and each caller to it.

**Comment by IgnoredAmbience** [comment]
Test for pattern binders added in 9c8d4c3

**Comment by IgnoredAmbience** [comment]
Fix committed in fe7d1526

**Comment by IgnoredAmbience** [comment]
Do not use the environment to detect shadowing: detect shadowing for the wrong reason.

The only time a var is not fine is a match for the same value. Non-monadic let with the same value.

Restrict shadowing check.

1) Handle our own list of variable declarations. List of things declared in current JS scope.
2) Disable shadowing.
3) Name reuse in monadic calls are not shadowed, so should be fine.

**Comment by brabalan** [comment]
Alternative approach: do automatic renaming to avoid shadowing
- we carry a map around of shadowed names to their renaming
- `ppf_ident` takes an additional argument
   - `None`: do not rename (used when calling it for binders)
   - `Some m`: use the map m to rename the identifier
- `do_check_shadowing` takes the map as argument and use it to compute the renamed name, it returns the updated map

**Comment by IgnoredAmbience** [comment]
Function argument patterns do not need a shadowing check, as they shadow in both JS and ML.

**Comment by brabalan** [comment]
Todo
- change `ppf_match_binders` to always introduce `var`

**Comment by IgnoredAmbience** [comment]
Scoping still possibly broken. In jsjsref, running the following test results in a failed heap lookup in the first field dereferencing. This is resulting from a location being compared with an object value. Somewhere a type-cast hasn't stuck. This is either due to the type-casting function being incorrectly compiled, or more likely due to miscompilation of the complex scoping of the `base` variable in `get_value` in JsInterpreter.ml.

`base` is rebound 5 separate locations in this function.

```js
var x = { a : { c : 1 } };
x.a.b = 2;
x.a.x = x;
x```

**Comment by IgnoredAmbience** [comment]
`get_value` is miscompiled. In particular:
```js
let_ret(..., function(_tuple_arg_5) {
  var base𝟙 = _tuple_arg_5[1];
  var s𝟘 = _tuple_arg_5[0];
  return ( object_internal_get(s, base𝟘, get_referenced_name(v𝟘), get_this_value(v𝟘)));
})
```
corresponds to
```ocaml
let%ret (s, base) = ...
in object_internal_get s base (get_referenced_name v) (get_this_value v)
```
It would appear that a tuple pattern in a monadic let binding is not updating the shadowing map.

**Comment by IgnoredAmbience** [comment]
Whilst fixing this, I've noticed much duplicated code for various sections of the compiler, particularly in function compilation having a monad special case.

I'm also finding that mixing in of logged, unlogged, token generation and psuedocode modes make reading the core compilation code extremely hard to read. In the long run it may be worth refactoring the code generation to output to a JS AST, which then has further passes to generate the various variants of output.
