### ISSUE TITLE
make test_init & npm dependencie

### ISSUE THREAD

**Issue by barockobamo** [jscert/jsexplain#27]
This is my configuration :
+ Fresh debian install (Debian GNU/Linux 9 (stretch))
+ node version : v8.11.4
+ npm version : v5.6.0

Here is the output :
$ make test_init
git submodule update --init test/data/test262
Sous-module 'test/test262' (https://github.com/tc39/test262.git) enregistré pour le chemin 'test/data/test262'
Clonage dans '/home/sam/git/jsexplain/test/data/test262'...
Chemin de sous-module 'test/data/test262' : '29e247ddd45a148f56be70b3d7120b7c5e649926' extrait
npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN notice [SECURITY] growl has the following vulnerability: 1 critical. Go here for more details: https://nodesecurity.io/advisories?search=growl&version=1.9.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=0.3.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> tripwire@4.1.0 install /home/sam/git/jsexplain/node_modules/tripwire
> node install.js

make[1] : on entre dans le répertoire « /home/sam/git/jsexplain/node_modules/tripwire/build »
  CXX(target) Release/obj.target/tripwire/src/tripwire_linux.o
make[1]: g++ : commande introuvable
tripwire.target.mk:96 : la recette pour la cible « Release/obj.target/tripwire/src/tripwire_linux.o » a échouée
make[1]: *** [Release/obj.target/tripwire/src/tripwire_linux.o] Erreur 127
make[1] : on quitte le répertoire « /home/sam/git/jsexplain/node_modules/tripwire/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-7-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sam/git/jsexplain/node_modules/tripwire
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN jsjsref@1.0.0 No repository field.
npm WARN jsjsref@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tripwire@4.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tripwire@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sam/.npm/_logs/2018-09-04T13_27_17_154Z-debug.log
Makefile:25 : la recette pour la cible « test_init » a échouée
make: *** [test_init] Erreur 1

Before this test i did not know tha npm was a dependence and there was another error.
If the Makefile install npm maybe a fix is needed for this OS. 
If the user has to do it maybe an information is needed somewhere.

**Comment by IgnoredAmbience** [comment]
The issue lies with [tripwire](https://github.com/tjanczuk/tripwire) for nodejs no longer being supported/developed. I removed it from the es2016-proxies branch, along with updating the other dependencies.
This should be fixed once #3 merges to master. I'll discuss this in the next meeting with Alan. (But I see few reasons not to do it).

**Comment by barockobamo** [comment]
ok, should i close this issue or keep it ?
