### ISSUE TITLE
Makefile wildcards expension failed when dash is the sh shell

### ISSUE THREAD

**Issue by barockobamo** [jscert/jsexplain#33]
This happen on many of my debian machines.
The clean section of Makefile was not able to execute 
these kind of command :
clean :
	rm -f *.{cmi, cmo}
We found out that we should ever :
- change them as follow rm -f *.cmi *.cmo (Maybe the simplest way)
- force the shell in Makefile
- detect the shell and use different case (The worst way for my opinion)

**Comment by IgnoredAmbience** [comment]
Ah, I hadn't tested using dash before. I'm happy with the first option.

**Comment by brabalan** [comment]
As it seems that `/bin/sh -> dash` is the default on debian, we should not use curly braces expansion.

**Comment by barockobamo** [comment]
Removed Makefiles wildcard in clean section in #34
